#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/subhrom1/testhelpx.git"

strains:
  - name: default
    code: *defaultRepo
    content:  https://github.com/subhrom1/testhelpxcontent#master
    static: *defaultRepo
